### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#105]
@gemmabusoni is awesome and has somehow secured a free large printed banner for us. We just need to send her what to print on it.

@MaxWofford can you take point on this and coordinate with @gemmabusoni for the artwork's requirements?

/cc @jonleung

**Comment by zachlatta** [comment]
@MaxWofford any updates on this?

**Comment by MaxWofford** [comment]
@zachlatta Sorry for not posting it here. I've been working with @gemmabusoni over PM. I'll move the conversation here.

**Comment by zachlatta** [comment]
Awesome! Thanks.

Remember you can always say:

    steward notify me on mentions

To get Steward to ping you on all mentions on GitHub issues.

On Mon, Aug 24, 2015 at 2:10 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Sorry for not posting it here.
> I've been working with @gemmabusoni <https://github.com/gemmabusoni> over
> PM. I'll move the conversation here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/105#issuecomment-134381241>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
:+1:

**Comment by MaxWofford** [comment]
@gemmabusoni Is this time sensitive? I'll be busy until Sept. 8th and may not be able to finish this.

**Comment by zachlatta** [comment]
Ideally we'd have it by this Friday.

@gemmabusoni, would it be possible to have this sometime next week?
Potential logo change.

On Tuesday, August 25, 2015, Max Wofford <notifications@github.com> wrote:

> @gemmabusoni <https://github.com/gemmabusoni> Is this time sensitive?
> I'll be busy until Sept. 8th and may not be able to finish this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/105#issuecomment-134835757>.
>


-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
@zachlatta I can design a banner tonight for either logo, but I'll need some specs.

@gemmabusoni What are the constraints on printing? (size, number of colors, etc.)

**Comment by gemmabusoni** [comment]
@MaxWofford 
6 feet by 3 feet
full color
2 files: one  EPS and one PDF
Also: do we want groomlets only on the corners or 3 on top and 3 on the bottom?

**Comment by zachlatta** [comment]
I've talked with each of you independently about the potential "Hack Club"
rename.

Let's hold off on this until we decide whether we'll go ahead and move
forward with it.

On Fri, Aug 28, 2015 at 1:23 AM, Gemma Busoni <notifications@github.com>
wrote:

> @MaxWofford <https://github.com/MaxWofford>
> 6 feet by 3 feet
> full color
> 2 files: one EPS and one PDF
> Also: do we want groomlets only on the corners or 3 on top and 3 on the
> bottom?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/105#issuecomment-135670872>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, I would actually like to postpone any serious renaming until we've consulted more people about it. From consulting one person yesterday, their recommendation was to _not_ rename it to something more specific like "Hack Club" because it prevents us from doing other things besides clubs in the future.

**Comment by MaxWofford** [comment]
I'll be gone until September 9th. Assigning to @zachlatta

**Comment by MaxWofford** [comment]
Closing this issue for the time being. @gemmabusoni If this opportunity is still open feel free to  reopen it
