### ISSUE TITLE
Schedule time with Selynna to discuss involvement this next semester

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#107]
/cc @jonleung @ssun098

**Comment by ssun098** [comment]
@zachlatta let's irc about this?

**Comment by zachlatta** [comment]
@ssun098 Would you prefer we do this? I think it'd be valuable to include @jonleung in this discussion (potentially @hellyeah and @MaxWofford as well).

**Comment by zachlatta** [comment]
Not sure if IRC would be the best medium for that much synchronous communication.

**Comment by ssun098** [comment]
Yeah this is totally fine

**Comment by zachlatta** [comment]
From IRC in PM:

> 7:57 PM <zrl> could we do a hangout?
> 7:57 PM <ssun> right now?
> 7:57 PM <zrl> i'd schedule a time that works for everyone?
> 7:57 PM <ssun> sure
> 7:57 PM <ssun> do you think everyone could do a weekend?
> 7:57 PM <zrl> weekend may be difficult :-/
> 7:58 PM <zrl> how about i talk with everyone, hear their ideas, then set a time that works for you (perhaps during weekend) between you and me
> 7:58 PM <ssun> sure
> 7:58 PM <ssun> if weekend is hard i can do weekdays
> 7:59 PM <ssun> so don't push for weekends if it's inconvenient :) 
> 7:59 PM <zrl> alright, cool. i'll find a time and let you know! thank you for being flexible.

**Comment by hellyeah** [comment]
I don't think everyone would need to be in this meeting. My two cents are that Selynna is awesome and that I'd love to work with her more closely day-to-day if she was interested in getting more involved with hackEDU.

**Comment by jonleung** [comment]
:+1:

**Comment by MaxWofford** [comment]
Same here.

**Comment by zachlatta** [comment]
I think her role has clarified since, closing for now.
