### ISSUE TITLE
Add GitHub notifications via Steward to the flow of onboarding a new team member

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#114]
In the flow for onboarding a new team member, we should add the GitHub Steward notification feature (the one that sends you a PM whenever you are mentioned in a GitHub notification).

This will allow the new team member to only have to remember to check one place, IRC, not two (IRC & GitHub).

Thoughts @zachlatta?

**Comment by zachlatta** [comment]
What if we created a new heading called `Managing GitHub Notifications` and
mentioned Steward and email filters without saying they should do one or
another?

On Wed, Aug 26, 2015 at 5:59 PM, Jonathan Leung <notifications@github.com>
wrote:

> In the flow for onboarding a new team member, we should add the GitHub
> Steward notification feature (the one that sends you a PM whenever you are
> mentioned in a GitHub notification).
>
> This will allow the new team member to only have to remember to check one
> place, IRC, not two (IRC & GitHub).
>
> Thoughts @zachlatta <https://github.com/zachlatta>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/114>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta sounds good to me!

**Comment by zachlatta** [comment]
Cool, let's do this. This should be in `onboarding_protocol.md`.

**Comment by paked** [comment]
Can directors get this too?

**Comment by MaxWofford** [comment]
@paked Yep! Check out https://github.com/hackedu/meta/pull/139/files
