### ISSUE TITLE
Update contribution guidelines

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#115]
Can you add something like: "If you have made a Pull Request that you want merged, assign someone on the core team to it?"

**Comment by MaxWofford** [comment]
I'd be happy to have it default to assigning to me; I'm usually working on misc. tasks.

**Comment by zachlatta** [comment]
One thing to note is that people who don't have write access to the repo
won't be able to assign any of us to pull requests they submit.

On Wed, Aug 26, 2015 at 8:14 PM, Max Wofford <notifications@github.com>
wrote:

> I'd be happy to have it default to assigning to me; I'm usually working on
> misc. tasks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/115#issuecomment-135270788>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
I'll be gone until September 9th. Assigning to @zachlatta

**Comment by zachlatta** [comment]
Decided against doing this because when we had cohort 1 of Labs submit pull requests to add themselves to https://github.com/hackedu/hackedu/tree/master/meta/labs#lab-directors, all seemed to work out as-is.
