### ISSUE TITLE
Olark IRC chat on hackEDU website

### ISSUE THREAD

**Issue by hellyeah** [hackedu/meta#128]
@jonleung something we can iframe that looks really pretty

First idea:
iframe embed

**Comment by MaxWofford** [comment]
@hellyeah Because this is a improvement to the website specifically, perhaps this issue could be transferred to hackedu/website.

**Comment by zachlatta** [comment]
@MaxWofford can you move it to `hackedu/website`?

**Comment by MaxWofford** [comment]
This has been migrated to https://github.com/hackedu/website/issues/164
