### ISSUE TITLE
Community Goals for Week of 09.07.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#129]
- [ ] 5 organic posts with discussion in FB group
- [ ] 10 introduction posts
- [ ] 5 Medium posts

**Comment by hellyeah** [comment]
Going to try to get Labs Leaders to write "Hello, World" posts today.

**Comment by zachlatta** [comment]
Sounds great!

On Thu, Sep 10, 2015 at 7:18 AM, David Fontenot <notifications@github.com>
wrote:

> Going to try to get Labs Leaders to write "Hello, World" posts today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/129#issuecomment-139248609>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Uncertain how to close this and say that I missed the goals?

**Comment by zachlatta** [comment]
Let's go with that for now. Going to close since last week is over.
