### ISSUE TITLE
One sheet is missing a testimonials section

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#13]

**Comment by zachlatta** [comment]
Is this still necessary? @jonleung

**Comment by zachlatta** [comment]
Closing due to lack of progress.

**Comment by MaxWofford** [comment]
@ZachLatta could you please elaborate on `lack of progress`?

**Comment by zachlatta** [comment]
The issue was opened three months ago and when I pinged @jonleung to check in on progress two months ago there was no response. Happy to reopen if we plan on implementing this.
