### ISSUE TITLE
Link CONTRIBUTING.md in README.md

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#131]
`hackedu/hackedu/README.md` does not tell me how to contribute. It should link me to `CONTRIBUTING.md`

**Comment by MaxWofford** [comment]
Will submit a PR for this soon.

**Comment by zachlatta** [comment]
One thing about this – GitHub tells you how to contribute. Whenever you
create an issue or a pull request, GitHub has a big yellow banner telling
you to read CONTRIBUTING.md.

On Wed, Sep 9, 2015 at 11:28 AM, Max Wofford <notifications@github.com>
wrote:

> Will submit a PR for this soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/131#issuecomment-138998795>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
Closing this issue because the fix was merged in hackedu/hackedu#178
