### ISSUE TITLE
Build chrome extension for moving github issues

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#132]
_From @hellyeah on September 9, 2015 17:9_

https://github.com/google/github-issue-mover/issues/110

_Copied from original issue: hackedu/hackedu#177_

**Comment by zachlatta** [comment]
`hackedu/meta` or personal notes may be a better place for this issue because this doesn't have to do with the playbook's creation.

**Comment by hellyeah** [comment]
This would be cool, but is relatively unimportant, so I'm closing it for now.
