### ISSUE TITLE
Make fontebot for #hackEDU irc

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#133]
_From @hellyeah on September 8, 2015 16:55_

Talk to hardmath and max

_Copied from original issue: hackedu/hackedu#172_

**Comment by zachlatta** [comment]
_From @MaxWofford on September 9, 2015 21:54_

@hellyeah What does this issue mean?

**Comment by zachlatta** [comment]
Going to move this to `hackedu/meta` because it doesn't have to do with our existing clubs.

I'd bias towards having this be a personal note, rather than an organization issue.

**Comment by hellyeah** [comment]
Add welcome functionality to Steward and think of a better name for Steward in general. I'm closing this issue so that we communicate on https://github.com/hackedu/hackedu/issues/312
