### ISSUE TITLE
hackEDU Meetup at MHacks

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#134]
_From @hellyeah on September 8, 2015 17:8_

What club leaders will be at MHacks?

_Copied from original issue: hackedu/hackedu#174_

**Comment by hellyeah** [comment]
Will do this on bus to MHacks. 

Coordinating w/ @jonleung

**Comment by jonleung** [comment]
People I think are going to PennApps from hackEDU:

- Selynna
- Neil Chen
- Shriyash Jalukar
- Grace Zhang (isn't part of hackEDU but you talked with her)
- Rohith Varanasi
- Raphael Kats
- Bogdan Vitoc

@hellyeah, I'm happy to reach out to Bogdan and Selynna about this and have them lead the charge if you like? Down for other ideas as well!

/cc @hellyeah

**Comment by jonleung** [comment]
Moving forward with this to make sure there's enough time:

I just messaged Bogdan and Selynna asking if they wanted to organize.

**Comment by jonleung** [comment]
@ssun098 said she's down to take lead on this.

@zachlatta, how do I assign this to her?

**Comment by ssun098** [comment]
Oh @zachlatta could you add me as a contributor to this repo? It's the reason why I can't be assigned to anything

**Comment by jonleung** [comment]
@ssun098 yo! Awesome job with the meetup! Do you want to add some notes to this issue before you close it?

Wohoo!

**Comment by ssun098** [comment]
Thanks @jonleung! Let's close this after I write my Medium article about it.

**Comment by hellyeah** [comment]
Closing this issue because this event has already happened.

@ssun098 has decided to write a recap on Medium that we're tracking in #218
