### ISSUE TITLE
Check in with every Labs Leader

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#135]
_From @hellyeah on September 8, 2015 17:0_

_Copied from original issue: hackedu/hackedu#173_

**Comment by zachlatta** [comment]
Going to move this to `hackedu/meta` because it's not directly applicable to the playbook.

**Comment by hellyeah** [comment]
Need to merge in notes to issues on /clubs

**Comment by hellyeah** [comment]
This is going to be a recurring issue. Should I just make a new one every week or is better to just reflect this work in the issues in /clubs?

**Comment by zachlatta** [comment]
Let's make a new one every week.

**Comment by zachlatta** [comment]
Closed because this issue was from last week.
