### ISSUE TITLE
Schedule weekly calls with hackEDU Cohort 1 & 2

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#137]
This is something that we discussed doing before but never executed on.

A weekly call time has been setup for:

- [ ] Cohort 1 by Harrison
- [ ] Cohort 2 by Vene

/cc @hellyeah @zachlatta

**Comment by hellyeah** [comment]
We should have a point person in each cohort who takes this on.

Someone who's organized and always available.

**Comment by jonleung** [comment]
@zachlatta, I'm happy to take this task for Harrison and Vene, thoughts?

**Comment by zachlatta** [comment]
Sounds good.

**Comment by jonleung** [comment]
@paked is going to work on this when he gets a chance. He's currently very busy. Because this task is not complete, I won't check off cohort 1's checkbox.

I reached out to Victor to see if I can chat with him over the phone to talk about this. Waiting for a response.

**Comment by zachlatta** [comment]
:+1:

On Thu, Sep 10, 2015 at 3:25 PM, Jonathan Leung <notifications@github.com>
wrote:

> @paked <https://github.com/paked> is going to work on this when he gets a
> chance. He's currently very busy. Because this task is not complete, I
> won't check off cohort 1's checkbox.
>
> I reached out to Victor to see if I can chat with him over the phone to
> talk about this. Waiting for a response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/137#issuecomment-139399636>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Just had a call with Victor to confirm this.

Status now is that both @paked and Victor are aware of the plans and will most likely execute on this this coming week.

**Comment by paked** [comment]
Can confirm. Am @paked.

This will be done ASAP.

**Comment by paked** [comment]
OK. I'm setting this up now. Just pinged the messenger chat to generate some interest.

**Comment by paked** [comment]
Progress update: We are having an initial call at some point this weekend. Most people seem interested.

**Comment by zachlatta** [comment]
Can you push to get everyone on that call? I think it's important that we
set the precedent that the cohort is as only strong as its weakest link
from the very beginning.

On Tue, Sep 15, 2015 at 2:54 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Progress update: We are having an initial call at some point this weekend.
> Most people seem interested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/137#issuecomment-140557768>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by paked** [comment]
@zachlatta I'm going to try. However it seems that me doing it doesn't have
the same prestige, as say you or @jonleung organizing it. IMO this is
something which will have to be built upon, instead of starting strong from
day 1.

**Comment by jonleung** [comment]
I agree with @paked that if this is organic, it will be hard to get everyone to be on the call.

The call just happened earlier today and wasn't too successful. I'll leave @Bogidon to comment why.

**Comment by jonleung** [comment]
I'm leaving this an open issue here because I'll be doing work throughout the week to make sure that another hopefully more successful call happens next week.

**Comment by zachlatta** [comment]
Can you close this and create a new issue to track the call for this week?
I think that may be a bit more clear.

On Sat, Sep 19, 2015 at 7:32 PM, Jonathan Leung <notifications@github.com>
wrote:

> I'm leaving this an open issue here because I'll be doing work throughout
> the week to make sure that another hopefully more successful call happens
> next week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/137#issuecomment-141729978>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, yup I added your suggestion to my queue of work.

**Comment by jonleung** [comment]
Closing because @zachlatta made a new issue for this week's sprint.
