### ISSUE TITLE
Add setting up IRCCloud push notifications to onboarding flow

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#138]
Context: @hellyeah had no idea that push notifications existed for IRCCloud and wished to himself that it did.

/cc @zachlatta

**Comment by zachlatta** [comment]
Do you mean getting push notifications on every message in a channel?

On Thu, Sep 10, 2015 at 1:38 PM, Jonathan Leung <notifications@github.com>
wrote:

> Context: @hellyeah <https://github.com/hellyeah> had no idea that push
> notifications existed for IRCCloud and wished to himself that it did.
>
> /cc @zachlatta <https://github.com/zachlatta>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/138>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
I mean setting up normal push notifications. (Apparently they weren't turned on for @hellyeah—is that accurate?)

**Comment by MaxWofford** [comment]
Closing this because we moved to slack
