### ISSUE TITLE
Find out which Labs clubs have meetings this week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#148]
Make sure to also find out how many meetings they've ran so far and what they did in those meetings so we know if their upcoming meeting is a workshop or project day.

Can you comment below with a bullet point list so we know?

/cc @jonleung

**Comment by hellyeah** [comment]
Lowell - 9/17/2015
Cypher - 09/18/2015

**Comment by hellyeah** [comment]
Harrison and Leila's clubs are both still delayed. Gemma and Bogdan already started.

**Comment by zachlatta** [comment]
So Gemma and Bogdan have meetings as well?

**Comment by hellyeah** [comment]
@zachlatta they already had their first meetings last week.

**Comment by zachlatta** [comment]
Gotcha, sounds good.

Can you say which days people are meeting this week?

**Comment by jonleung** [comment]
Jiahao, Gemma, and Bogdan have meetings this week (and will continue to)

**Comment by zachlatta** [comment]
Sorry, so just to clarify. The following people have meetings this week:

- Jeremy/Teagan @ Lowell
- Gemma @ Hybrid High
- Jevin @ Cipher
- Bogdan @ Cherry Hill High
- Jiahao @ San Leandro High

Is that correct? Also, do we know which days of the week each of them are
meeting? I know @hellyeah got the day for Lowell and Cipher, but what about
the rest?

On Wed, Sep 16, 2015 at 9:10 AM, Jonathan Leung <notifications@github.com>
wrote:

> Jiahao, Gemma, and Bogdan have meetings this week (and will continue to)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/148#issuecomment-140790294>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by gemmabusoni** [comment]
USC Hybrid High School, every Tuesday from 4:00 pm to 5:00 pm; excepts testing days or no classes.

**Comment by hellyeah** [comment]
@zachlatta @tejasmanohar also had a meeting. All meetings have been reflected in clubs.hackedu.us

**Comment by tejasmanohar** [comment]
Tejas Manohar @ Ravenwood High School, every Thursday 2:30 -> 3:30 pm Central.

**Comment by jonleung** [comment]
@hellyeah should this issue be closed because

> All meetings have been reflected in http://clubs.hackedu.us
