### ISSUE TITLE
Create MVP of platform for feedback and attendance for use this week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#150]
This should include two things:

- Feedback forms
- Attendance

Coordinate with @hellyeah and @jonleung to make sure this is used this week.

**Comment by MaxWofford** [comment]
The mvp of this is live: http://feedback.hackedu.us/

**Comment by zachlatta** [comment]
:+1:

On Tue, Sep 15, 2015 at 1:47 PM, Max Wofford <notifications@github.com>
wrote:

> The mvp of this is live: http://feedback.hackedu.us/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/150#issuecomment-140534295>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by ad510** [comment]
The page doesn't look right in Firefox. (It looks good in Chrome and Safari.)

**Comment by zachlatta** [comment]
Looks great! Couple quick comments:

![tmp_2](https://cloud.githubusercontent.com/assets/992248/9892638/a43e4a2a-5bc5-11e5-9147-21f3d4376c90.png)

**Comment by MaxWofford** [comment]
@zachlatta Addressed your comments in https://github.com/hackedu/packrat/commit/26ee736bac4fa3cd7ee75f97b6a68c73d17cb9c0

**Comment by ad510** [comment]
I noticed that "Please answer as honestly as you feel comfortable" is a little awkward because it implies people might not want to answer honestly. Did you mean "in as much detail" instead of "as honestly"?

**Comment by zachlatta** [comment]
Good call, I think "in as much detail" is clearer.

On Tue, Sep 15, 2015 at 6:31 PM, Andrew Downing <notifications@github.com>
wrote:

> I noticed that "Please answer as honestly as you feel comfortable" is a
> little awkward because it implies people might not want to answer honestly.
> Did you mean "in as much detail" instead of "as honestly"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/150#issuecomment-140594336>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
https://github.com/hackedu/packrat/commit/bff70e25cff55e5ded521e3e889aff1a168399da

**Comment by jonleung** [comment]
Max, should this issue be closed because it is checked off here: meta/issues/150?

**Comment by MaxWofford** [comment]
@jonleung Yep! Thanks for linking that.
