### ISSUE TITLE
Styleguide should include 3 space indentation rules for ordered lists

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#152]
```
1. first
2. second
   1. child
```
instead of
```
1. first
2. second
  1. child
```

**Comment by zachlatta** [comment]
I know I've definitely indented 3 spaces on ordered lists, but I actually
think we should keep it to 2 space indentation universally. Thoughts?

On Thu, Sep 17, 2015 at 1:52 PM, Max Wofford <notifications@github.com>
wrote:

> 1. first
> 2. second
>    1. child
>
> instead of
>
> 1. first
> 2. second
>   1. child
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/152>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
2 spaces sounds good

**Comment by zachlatta** [comment]
Cool, let's plan on doing this.
