### ISSUE TITLE
Ensure Cohort 2 call is scheduled

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#158]
Correspond w/ Victor to plan this. This issue can be closed once the event is scheduled on the `Labs` calendar (#156).

**Comment by hellyeah** [comment]
Victor suggested Saturday at noon. Waiting on 3 people to confirm.

**Comment by jonleung** [comment]
@hellyeah @gemmabusoni, there are many people that are asking about the cohort 2 call, @hellyeah will just take lead on scheduling this call.

**Comment by hellyeah** [comment]
Call happened. Pinged leaders individually and encouraged them to chime in.

Vene took the lead with the help of @gemmabusoni.

@jonleung and @MaxWofford were also on the call.
