### ISSUE TITLE
Make images in one sheet retina

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#16]

**Comment by jonleung** [comment]
I'm going to hold off on this
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

jonl.org | 610-761-0083

**Comment by zachlatta** [comment]
@MaxWofford can you take lead on this?

**Comment by MaxWofford** [comment]
Yes. I'll make the changes.

**Comment by zachlatta** [comment]
<3

**Comment by zachlatta** [comment]
@MaxWofford what's the status on this?

**Comment by MaxWofford** [comment]
@zachlatta I can :shipit: when I get back in SF on the 9th.

**Comment by jonleung** [comment]
@zachlatta, I'm going to close this issue because it is not priority, please reopen if you feel otherwise

**Comment by zachlatta** [comment]
Let's leave open because it's an active issue with activity and @MaxWofford said he'll take care of it on the 9th.

**Comment by MaxWofford** [comment]
Closing this because it is not high leverage right now.
