### ISSUE TITLE
Ensure cohort 1 call is scheduled week of 09.28.15

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#162]

**Comment by gemmabusoni** [comment]
Cohort 1 call is scheduled for Friday at 4PM PST!

**Comment by paked** [comment]
@gemmabusoni I was thinking, should we create a calendar event for this? Invite everyone just to make sure no one forgets?

**Comment by zachlatta** [comment]
Closing because the call happened! I do like @paked's idea though.
