### ISSUE TITLE
Ensure that Packrat is used at all of the meetings this week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#164]
Meetings this week, per the club schedule calendar by @hellyeah:

Goal:
- [ ] 3:15PM PDT Thursday, San Leandro High School (Jiahao)
- [ ] 3:30PM PDT Thursday, Lowell High School (Teagan)

Stretch:
- [ ] 11:30AM PDT Monday, Cherry Hill East (Bogdan)
- [ ] 4:00PM PDT Tuesday, USC Hybrid School (Gemma)
- [ ] 10:30PM PDT Tuesday, Glenaeon Rudolf Steiner School (Harrison)
- [ ] 11:30PM PDT Wednesday, Cherry Hill East (Bogdan)
- [ ] 12:30PM PDT Friday, Ravenwood High School (Tejas)

**Comment by MaxWofford** [comment]
@zachlatta Is there some way I can get access to the live version of packrat? It would make it much easier for me to see what's going on.

**Comment by ZucchiniZe** [comment]
@MaxWofford isn't it deployed to https://labs.hackedu.us/ currently?

**Comment by MaxWofford** [comment]
@ZucchiniZe I'd like to see what clubs we've been getting responses in.

**Comment by hellyeah** [comment]
@MaxWofford I don't think we even got a response from Bogdan's club this week.

**Comment by hellyeah** [comment]
Replaced by #207
