### ISSUE TITLE
Schedule time to talk about switching to Slack

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#165]

**Comment by paked** [comment]
@zachlatta thoughts on opening this up as a discussion with everyone?

**Comment by zachlatta** [comment]
Definitely open to it. I'll post the time and hangout URL here and anyone's welcome to join.

**Comment by zachlatta** [comment]
Alright, we'll be hosting this discussion in https://partytime.hackedu.us from 1-2PM PDT tomorrow. Anyone's welcome to join :-).

**Comment by paked** [comment]
@zachlatta I'll try and be awake. If not, be sure to post to IRC... There are some people with communications opinions in there :laughing:
