### ISSUE TITLE
Schedule time to talk about our PR workflow with the entire team

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#166]

**Comment by zachlatta** [comment]
Waiting on @MaxWofford to send me an agenda for this meeting.

**Comment by zachlatta** [comment]
@MaxWofford will be taking point on scheduling this meeting and leading it.

**Comment by MaxWofford** [comment]
I've  just scheduled a meeting time in the team calendar and signed us up for the panhandle on the 4th floor.
