### ISSUE TITLE
Talk with Selynna and Sam to plan for HackingEDU

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#172]
/cc @ssun098 @saescapa

**Comment by ssun098** [comment]
Hey! What needs to be planned?

**Comment by saescapa** [comment]
Same here! Let me know how I can help!

**Comment by gemmabusoni** [comment]
Scheduling call with @ssun098 @saescapa; will potentially be held tomorrow.

**Comment by saescapa** [comment]
@gemmabusoni Just to clarify, @ssun098 and I will be giving a small speech about hackEDU at the hackingEDU open ceremony?

**Comment by paked** [comment]
That doesn't sound like brand confusion at all!

**Comment by ssun098** [comment]
@paked Literally the same right?!

**Comment by gemmabusoni** [comment]
Update: held call with @saescapa and @ssun098. 

@saescapa yep!

**Comment by ssun098** [comment]
@gemmabusoni do you know about how long this talk should be?

**Comment by hellyeah** [comment]
Would be cool to have a HS Hackers meetup

**Comment by hellyeah** [comment]
High priority for next week. Most people don't know about it. We have 75 seats.

**Comment by gemmabusoni** [comment]
@ssun098 Think we'll have about a minute. Checking with Keero, and then I'll follow up with you.

HS Hackers meetup would be awesome. I can set up the event, but it might be ideal to have Selynna or @saescapa (or both!) lead that.

**Comment by ssun098** [comment]
@hellyeah @gemmabusoni already taken care of. Scheduled.for 2am saturday,
I'm organizing

**Comment by paked** [comment]
omg. I can attend that time! hangout me in!

**Comment by zachlatta** [comment]
We :heart: you @paked

**Comment by paked** [comment]
:heart: @zachlatta

**Comment by ssun098** [comment]
@saescapa do you want to help me organize the hshackers meetup?

**Comment by saescapa** [comment]
@ssun098 Sure! Aren't there a ton of HS hackers coming?

**Comment by ssun098** [comment]
@saescapa yeah I think so! Let's talk when I see you Saturday
