### ISSUE TITLE
Record workshops being run by each Labs club this week in https://clubs.hackedu.us

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#175]
If there isn't already an entry for their meeting, create one in the `Meetings` sheet in https://clubs.hackedu.us and record which workshop they're running in the curriculum plans column.

**Comment by jonleung** [comment]
Done. 

Here is the link to the [meetings sheet](https://docs.google.com/spreadsheets/d/1Mb-8WBjiZUOYgWqNJxaigCWZvZqnIHZ2ZhokVNCbJ4g/edit#gid=1932846329).
