### ISSUE TITLE
Schedule weekly team lunches for Mondays

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#187]

**Comment by paked** [comment]
This sounds so cute. :disappointed:

**Comment by MaxWofford** [comment]
@zachlatta Thought we decided against this because it makes a different dynamic between the in-person team and the remote team.

**Comment by zachlatta** [comment]
Calendar invites sent!

@MaxWofford we're experimenting with a more remote-friendly workflow (more meetings on Hangouts and meetings directly on IRC) and we want to make sure that there's still unity within the in-person team. I definitely want this to be an open conversation though, so don't hesitate to voice any concerns!
