### ISSUE TITLE
Create conditional formatting to visually separate each week in the "Meetings" sheet https://clubs.hackedu.us

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#203]

**Comment by paked** [comment]
This is something I could do!

**Comment by paked** [comment]
Oh wait... Nevermind. Thought this was a packrat issue.

**Comment by zachlatta** [comment]
Done! The sheet now automatically makes every other week grey.

I'm sure we'll have plenty to do on Packrat in the future @paked :-)
