### ISSUE TITLE
Slack <> IRC connection

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#209]
This issue tracks moving @paked's IRC <> Slack tunnel onto our servers

**Comment by paked** [comment]
When you want to initiate this process, give me a shout (probably in private on IRC) and I can send you the account details and `slack-irc` configuration file.

**Comment by MaxWofford** [comment]
Currently blocking on getting convox api token. Waiting for response in https://convox-public.slack.com/messages/convox/

**Comment by MaxWofford** [comment]
We're live!

![screenshot from 2015-10-13 11 57 48](https://cloud.githubusercontent.com/assets/5891442/10465036/ac314ef2-71a1-11e5-8317-43fa101f6f27.png)

**Comment by MaxWofford** [comment]
We're not live anymore :(

**Comment by paked** [comment]
I can start up my `slackEDU` again whenever she is needed.

**Comment by MaxWofford** [comment]
@paked That would be helpful! Thank you :)

**Comment by paked** [comment]
@maxwofford. done. Ping me when you want me to take it down again.

**Comment by zachlatta** [comment]
Booyah.

She's deployed.

https://github.com/hackedu/slackedu

**Comment by paked** [comment]
:+1:
