### ISSUE TITLE
Check in with club leaders to get feedback on hackEDU as a whole and synthesize the notes into written form

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#212]
Questions I may ask include:

- What is not working well for you now?
- What is not working for the club right now?
- What is the relationship like between you and your co-leads?
- What has been going well?
- Tell me about the experience as being part of the hackEDU community?
- What is the least clear thing about the workshops?
- What's the most valuable thing about being part of hackEDU right now?
- What is one thing that you wish we could do better?

After the calls, I need to synthesize the feedback into written form.

**Comment by jonleung** [comment]
I had two calls so far with 6 different club leaders.

**Comment by jonleung** [comment]
I'm leaving this issue open because I want to have more calls but checking it off in the weekly issue.

**Comment by jonleung** [comment]
Done! I made a follow up issue here: hackedu/hackedu#364

**Comment by jonleung** [comment]
I accidently closed this issue, re-opening.

**Comment by jonleung** [comment]
I have a call coming up to get moar feedback tomorrow!

**Comment by hellyeah** [comment]
4 calls so far. 2 more today.

**Comment by jonleung** [comment]
I talked with @zachlatta and I decided that this is not a high leverage task right now and opting for actually "doing things". I'm still going to continue looking through it myself but will be closing this issue.
