### ISSUE TITLE
Changing 'what are you blocking on' to 'what could you use help and/or are blocking on'

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#219]
As discussed with @jonleung, there is not a trigger in stand-ups for people to ask for help if they need  it. Changing 'what are you blocking on' to 'what could you use help and/or are blocking on' could be a trigger for this. Thoughts?

I can take point on stand-ups on Tuesday to set the standard for this question being asked.

/cc @hackedu/core

EDIT: updated question

**Comment by zachlatta** [comment]
I'm in!

**Comment by MaxWofford** [comment]
This added to  our documentation.

**Comment by jonleung** [comment]
@MaxWofford can you link to the pull request or the documentation? I was expecting to find it in hackedu/meta/README.md but it wasn't there.

The questions I think we should ask every standup are:

- What do we need to do to advance this piece of work?
- Is anyone working on anything that’s not on the board?
- What could you use help and/or are blocking on? Can we spot any impediments to the flow of work?

Note that "Can we spot any impediments to the flow of work?" is [straight from LeanKit](http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf)

Then @zachlatta could you add the questions to all of the standup events so the person leading standups has easy access to them?

**Comment by jonleung** [comment]
@zachlatta to clarify I meant to add the questions to all of the standup **calendar** events.

Also any updates @MaxWofford?

**Comment by MaxWofford** [comment]
Because the other questions from  standup are not documented, I'll opt to close this issue.
