### ISSUE TITLE
workshop guidelines should be documented in docs

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#22]

**Comment by MaxWofford** [comment]
What folder would be most suitable?

**Comment by zachlatta** [comment]
Perhaps /workshops?


On Thu, Mar 26, 2015, at 01:57 PM, Max Wofford wrote:
> What folder would be most suitable?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/hackedu/docs/issues/22#issuecomment-86712495

**Comment by zachlatta** [comment]
Closing for now due to lack of progress.

**Comment by MaxWofford** [comment]
@zachlatta Sorry for not following up on this; workshop guidelines became example workshops, which were added by @jonleung in his twilio-workshop repo.
