### ISSUE TITLE
Collaborate with @Bogidon on workshop making guidelines

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#221]
This can be closed when an MVP of the guidelines is shipped

**Comment by zachlatta** [comment]
Why won't we be fixing this?

**Comment by paked** [comment]
Yeah, this is still being worked on AFAIK

**Comment by MaxWofford** [comment]
@zachlatta @paked This was discussed at the morning meeting.  Waiting for a response from @jonleung on IRC so I can elaborate on this.
