### ISSUE TITLE
Zach reads Kanban Roadmap PDF

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#225]
@zachlatta, please read [this 26 page PDF](http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf) on how to do Kanban by the end of this sprint.

**Comment by zachlatta** [comment]
Done! So sorry for how long this has taken.
