### ISSUE TITLE
Max reads Kanban Roadmap PDF

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#226]
@MaxWofford, please read [this 26 page PDF](http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf) on how to do Kanban by the end of this sprint.

**Comment by jonleung** [comment]
@MaxWofford, hey! I was wondering when you will be able to finish reading this? (My task is to make sure everyone reads this by the end of the week #228)

**Comment by MaxWofford** [comment]
@jonleung I'll make sure to finish it by the end of the week.

**Comment by jonleung** [comment]
Hi @MaxWofford I am wondering why you closed this issue? Did you complete it? I want this issue to be open if it is not read yet and closed if it has been read.

**Comment by MaxWofford** [comment]
I've read the pdf
