### ISSUE TITLE
Dave reads Kanban Roadmap PDF

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#227]
@hellyeah, please read [this 26 page PDF](http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf) on how to do Kanban by the end of this sprint.

**Comment by hellyeah** [comment]
Will read on Caltrain to hackingEDU

**Comment by hellyeah** [comment]
Read.

**Comment by jonleung** [comment]
@hellyeah can you post your largest takeaways here?

**Comment by jonleung** [comment]
im reading this http://images.info.leankit.com/Web/LeanKitInc/%7B3128bbd1-0602-4459-8b2c-6efe02cdc1b9%7D_LeanKit-Kanban_Roadmap-2015.pdf and thought the most interesting part thus far has been about “pulling” work rather than “pushing” work through different steps of the process

hellyeah [9:43 AM]
cc @jonl @zrl @maxw

hellyeah [9:43 AM]
i like this too: "What to do when you run up against the WIP limit
When you hit a WIP limit, stop doing the kind of work that adds
to that queue. Instead, let the work continue to flow through the
system. Go help a teammate or work on a task that doesn’t add
WIP on the board. Go run some errands. Start an online class. But
whatever you do, don’t pile on more WIP at this point."

@jonl: I only have one. Pulling rather than pushing work.

hellyeah [9:59 AM]
2. We should have a dashboard that quantifies the board and velocity of it.
Team Directory
