### ISSUE TITLE
example club constitution should be added to docs

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#23]

**Comment by zachlatta** [comment]
+1 perhaps find a template for clubs online?

**Comment by MaxWofford** [comment]
Turns out many CS clubs already do this on [github](https://github.com/search?utf8=%E2%9C%93&q=+club+constitution)

**Comment by zachlatta** [comment]
:thumbsup: perhaps can "fork" one of them, make sure to check the repo's
license first.

--
Zach Latta Executive Director of hackEDU[1] http://zachlatta.com
https://github.com/zachlatta https://twitter.com/zachlatta


On Mon, Apr 6, 2015, at 06:39 PM, Max Wofford wrote:
> Turns out many CS clubs already do this on github[2]


> — Reply to this email directly or view it on GitHub[3].

>



Links:

  1. https://hackedu.us/
  2. https://github.com/search?utf8=%E2%9C%93&q=+club+constitution
  3. https://github.com/hackedu/docs/issues/23#issuecomment-90307876

**Comment by zachlatta** [comment]
@raphaelrk might have something that could be used as a template

**Comment by raphaelrk** [comment]
https://docs.google.com/document/d/1jvuNDaJASLbuxoc2Q6NepYHOKejy0Az-Z6ikAhpYxlM/edit?usp=sharing this was what we used for our club but I think it could use some improvement. Something to note is that all the clubs at my school have very similar bylaws. An individual club writing a constitution could have better luck looking at the constitutions of other clubs at their school through their school websites

**Comment by zachlatta** [comment]
Closed by hackedu/hackedu#15.
