### ISSUE TITLE
Each member of team takes three clubs and works with them to get attendance, feedback, and case studies for this week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#244]
This week we've decided to divide the 12 Labs clubs among the 4 of us, giving each of us 3 clubs to work with. Each of us will be responsible for working with our clubs to get attendance, feedback, and case studies for their meetings this week.

What must be gathered from each club for it to be considered successful for the week:

- Attendance (with names, emails, and phone numbers) of all attendees
- Some feedback from club members (we don't need feedback from every club member, though I think that'd be nice)
  - This can even be gotten from calls with one or two club members from each club
- A recap case study submitted in a pull request
  - They could submit a Google Doc to us and we covert it to Markdown and submit a PR ourselves
  - We could get on a call with them and write the case study coursers and submit it as a PR
  - They could submit the PR themselves

I've created the following issues to track each team member's clubs:

- @hellyeah hackedu/meta#247
- @jonleung hackedu/meta#245
- @MaxWofford hackedu/meta#248
- @zachlatta hackedu/meta#246

**Comment by MaxWofford** [comment]
Closing this because the week ended
