### ISSUE TITLE
@jonleung's clubs for the week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#245]
See #244 for full details.

Check off each club once the requirements in #244 are met. These are @jonleung's
clubs:

- [ ] ~~Ravenwood High School~~ _(their club meeting was also cancelled this week because Tejas is away)_
- [ ] ~~Cherry Hill High School East~~ (their club is not meeting this week because they are on break / prepping for CHE hacks)
- [ ] USC Hybrid High School _(I committed to remind Gemma at 4:45pm to submit feedback but didn't remind her until 4:53pm, I messed up. Also, there seemed to have been a login issue. @gemmabusoni could you describe what happened with the website loading?)_
- [ ] Lowell High School (Thursday, 3:30PM)

**Comment by gemmabusoni** [comment]
@zachlatta We are meeting tomorrow.

**Comment by jonleung** [comment]
Hey Gemma! Here is your reminder you requested to take attendance at 4:10pm in this spreadsheet: bit.ly/gemmarocks

I've sent you this message on FB Messenger as well.

<3 hackEDU

---

Hey Gemma! Here is your reminder you requested to collect feedback at 4:50pm!

Here is the link for members
https://labs.hackedu.us

You can tell them to only answer the below questions and skip everything else if they want
"Describe in one sentence what you worked on today. Include any links if applicable"
"Please rate from -5 to 5 how satisfied you are with today's club meeting"

Here's the link for you to see who's submitted
https://labs.hackedu.us/clubs/4

Don't forget to walk around to make sure each person fills out the feedback.

I've sent this to you on FB Messenger as well.

<3 hackEDU

**Comment by jonleung** [comment]
@gemmabusoni oops I crossed off the wrong school. I meant Cherry Hill. Thanks!

**Comment by jonleung** [comment]
@MaxWofford said that he would be able to take over the work associated with @gemmabusoni's club for me (namely the work of obtaining a case study).

**Comment by MaxWofford** [comment]
@jonleung https://github.com/hackedu/meta/issues/248#issuecomment-152791470
