### ISSUE TITLE
@zachlatta's clubs for the week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#246]
See #244 for full details.

Check off each club once the requirements in #244 are met. These are
@zachlatta's clubs:

- [ ] Glenaeon Rudolf Steiner School (Tuesday, 10:30PM)

**Comment by hellyeah** [comment]
@zachlatta, feel better. We got you.

Moving 
Lowell High School (Thursday, 3:30PM) to Jon: #245 
Glenaeon Rudolf Steiner School (Tuesday, 10:30PM) to Max: #248 
College Park High School (Thursday, 2:50PM) to Dave #247

**Comment by zachlatta** [comment]
Thank you @hellyeah!

**Comment by zachlatta** [comment]
(and everyone else on the team :heart:)

**Comment by jonleung** [comment]
Closing because the work here has been migrated to various other issues (see [this comment](https://github.com/hackedu/meta/issues/246#issuecomment-151940372))
