### ISSUE TITLE
@MaxWofford's clubs for the week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#248]
See #244 for full details.

Check off each club once the requirements in #244 are met. These are
@MaxWofford's clubs:

- [x] San Leandro High School
  - [x] Feedback
  - [x] Planning
  - [x] Recap
- [ ] Armijo High School
  - [x] Feedback
  - [ ] Planning
  - [ ] Recap
- [ ] South Brunswick High School
  - [ ] Feedback
  - [x] Planning
  - [x] Recap
- [ ] ~~Glenaeon Rudolf Steiner School (Tuesday, 10:30PM)~~ _(moved back to #246)_

**Comment by MaxWofford** [comment]
@zachlatta 

> These are @zachlatta's clubs:

**Comment by zachlatta** [comment]
Whoops, these are actually your clubs. My issue is the one that's incorrect.

**Comment by zachlatta** [comment]
I take that back. They were both correct.

**Comment by zachlatta** [comment]
I'm gonna steal Glenaeon Rudolf Steiner School back, since I've already been talking with him about this.

**Comment by MaxWofford** [comment]
As discussed with @jonleung, I'll be contacting @gemmabusoni about submitting her case study

**Comment by MaxWofford** [comment]
Closing this because the week ended.
