### ISSUE TITLE
Out of place language in FAQ

### ISSUE THREAD

**Issue by JacobEdelman** [hackedu/meta#25]
In https://github.com/hackedu/docs/blob/master/README.md#why-do-we-need-another-learn-to-code-organization the line " We need to create a community around hacking so the duplication doesn't happen. " seems out of place. In the values document this isn't mentioned anywhere.

**Comment by zachlatta** [comment]
Agreed that it's out of place. Want to submit a PR to remove it? The
README is super out of date and we haven't been maintaining it (we
should change this!).

**Comment by zachlatta** [comment]
Went ahead and redid the readme, removing most of the cruft and stuff we don't use anymore! See 8cb2567421c2ec584874b05c9ed2a02c119f0e92.
