### ISSUE TITLE
Delete gh-pages branch

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#255]
@hackedu/core Is there a reason we need a `gh-pages` branch for hackedu/meta?

**Comment by jonleung** [comment]
I may want to experiment with a gh-pages branch this very shortly.


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by MaxWofford** [comment]
@jonleung What will you be putting on it? Right now it is out of date by 191 commits, and has no content that can be hosted on gh pages (everything is in markdown).

**Comment by jonleung** [comment]
I will be using it later. Feel free to delete this branch and I can
re-create it when I need it.


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
