### ISSUE TITLE
Values and Mission Doc Needs Summarization

### ISSUE THREAD

**Issue by JacobEdelman** [hackedu/meta#26]
The Values and Mission doc seems to just be a single mission statement (good) followed by a long list of buzz wordy values (bad). I'd recommended choosing a few values (5 or so) to make your own and only focus on them. Right now it reads more like a catalogue of good ideas then a mission statement.

**Comment by zachlatta** [comment]
Agreed that we have far too many things in the values & mission doc. I
like your idea that we should choose a few, but I think we should
actually start with just 1 or 2 and work up from there. What are your
thoughts on that?

The first two that come to mind (and we've already been explicitly doing
these internally) are curiosity and integrity.

--
Zach Latta
Executive Director of hackEDU[https://hackedu.us/]
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by JacobEdelman** [comment]
Rather than integrity I'd go with something about openness. The HackEDU devotion to having everything open and online is an obvious and commendable virtue. I wouldn't use the actual word openness since that seems to convey acceptance. Curiosity is definitely a good one.

**Comment by zachlatta** [comment]
Agreed that openness is critical. What if we did curiosity,
transparency, and integrity?

**Comment by JacobEdelman** [comment]
:+1:
