### ISSUE TITLE
Find out what club leaders planned curriculum is and document it in https://clubs.hackedu.us in the Meetings sheet

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#262]
- [ ] ~~USC Hybrid High School~~ _Not meeting_
- [ ] Cherry Hill High School East
- [ ] ~~San Leandro High School~~ _Not meeting_
- [ ] Lowell High School
- [ ] Ravenwood High School
- [ ] Project Cipher
- [ ] College Park High School
- [ ] ~~South Brunswick High School~~ _Not meeting_
- [ ] ~~Columbia Secondary School~~ _Unable to contact_
- [ ] Glenaeon Rudolf Steiner School
- [ ] Elizabeth High School
- [ ] Armijo High School

EDIT by @MaxWofford: Added checkbox list off schools

**Comment by MaxWofford** [comment]
Get well soon @jonleung

**Comment by MaxWofford** [comment]
This can be closed with #268 andd #265
