### ISSUE TITLE
Grow slack messages by 10%

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#264]
_From @hellyeah on November 2, 2015 20:30_

@zachlatta we should discuss later today or tomorrow the exact query we want to do for stats. We should likely keep it simple to start. Maybe it doesn't even make sense to subtract out ourselves to start.

_Copied from original issue: hackedu/hackedu#447_

**Comment by hellyeah** [comment]
Zach is sending me daily PDFs ~midnight. I'm recording data in clubs.hackedu.us

**Comment by hellyeah** [comment]
Non-staff weekly messages (Mon-Mon):
3,020	3307	4362	4400	5402	0	6475	7510

**Comment by paked** [comment]
:+1: LETS KEEP THIS GOING
