### ISSUE TITLE
Get attendance number from 6 labs clubs

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#265]
_From @hellyeah on November 2, 2015 20:32_

- [x] Armijo High School (15)
- [ ] Cherry Hill High School 
- [x] Project Cipher (9)
- [x] Lowell High School (15)
- [x] Ravenwood High School (9)
- [x] Elizabeth High School (22)

_Copied from original issue: hackedu/hackedu#448_

**Comment by hellyeah** [comment]
Did not complete this task. Just messaged all the leaders.

**Comment by hellyeah** [comment]
No response from Bogdan

**Comment by MaxWofford** [comment]
@hellyeah Thanks for working on this!

![](https://media.giphy.com/media/6tHy8UAbv3zgs/giphy.gif)
