### ISSUE TITLE
aggregate attendance data

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#266]
Put together system to aggregate attendance data and put the data from last week into it

**Comment by zachlatta** [comment]
Note: this system should account for both the total attendee count of each club's meeting, but also each of the attendee's names and associated data (like their emails).

**Comment by MaxWofford** [comment]
@hellyeah Shipped at https://docs.google.com/spreadsheets/d/1iUWZxO6soZcoI3VVmSLSCFsl-3q76lfRMyvB5A7wQGE
