### ISSUE TITLE
@MaxWofford Get attendance number from 6 labs clubs

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#268]
_From @MaxWofford on November 2, 2015 20:57_

- [ ] ~~USC Hybrid High School @gemmabusoni~~ _Too many college apps, not meeting_
- [ ] ~~San Leandro High School @xeonjake~~ _Going on a field trip, not meeting_
- [ ] College Park High School @venethefifth _Waiting for response_
- [ ] ~~South Brunswick High School @sneharamapo~~ _Not meeting this week_
- [x] Columbia Secondary School @AbigailMed (8)
- [x] Glenaeon Rudolf Steiner School @paked 

_Copied from original issue: hackedu/hackedu#449_

**Comment by MaxWofford** [comment]
Assigning to @hellyeah so he can get attendance from @AbigailMed

**Comment by hellyeah** [comment]
Contacted on Messenger. 8 people.

**Comment by hellyeah** [comment]
No response from Vene.

**Comment by MaxWofford** [comment]
@hellyeah Thanks for taking point on this!

![](http://quickme.me/thanks.gif)
