### ISSUE TITLE
Renaming Repos

### ISSUE THREAD

**Issue by JacobEdelman** [hackedu/meta#27]
Zach's message which he asked me to post : "Perhaps rename docs to meta and then rename hackEDU to website and club-in-a-box to hackEDU?"
I (Jacob, not Zach now) think that the club-in-a-box repo (renamed to hackEDU) would be for general club discussions with discussion facebook transfered into it. The website would be for the website. The docs (renamed to meta) repo would be for discussion for running hackEDU and such.

**Comment by MaxWofford** [comment]
Definitely :+1: for `hackEDU` repo => `website`. 

Not sure about a `hackedu` repo inside `hackedu` organization; lots of organizations have a repo with the same name and many use them for completely different things. Maybe `club-in-a-box` => `club-discussions`?

**Comment by JacobEdelman** [comment]
My feeling was that `hackedu` is an organization about supporting clubs and having them collaborate so having the "main repo" be about that would be fine. In general it seems that repos named after organizations are the organizations main purpose or project, like the `docker/docker`. I think that a collaborative wiki / discussion area could be classified as hackedu's main purpose. What I also like about the naming is that it focuses newcomers on that project which is what we would want as the other projects would be more focused on management.

**Comment by zachlatta** [comment]
> Maybe club-in-a-box => club-discussions?

@MaxWofford do you think that captures the full purpose of what the `club-in-a-box` repo will contain? I like @JacobEdelman's idea of putting it at `hackedu/hackedu` because it gives the opportunity for expansion and is general enough for both club discussions and club resources.

**Comment by zachlatta** [comment]
What if we try doing the rename and seeing if it causes any issues? Worst case is we can rename back (and a few git remotes may be wonky).

@jonleung thoughts?

**Comment by zachlatta** [comment]
BOOM. Consider yourself renamed.

* `hackedu/hackedu` -> hackedu/website
* `hackedu/club-in-a-box -> `hackedu/hackedu`
* `hackedu/docs` -> `hackedu/meta`
