### ISSUE TITLE
Set up Steward on Slack

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#278]
_From @hellyeah on October 6, 2015 21:58_

_Copied from original issue: hackedu/hackedu#312_

**Comment by zachlatta** [comment]
_From @hellyeah on October 26, 2015 17:38_

Think of a cuter, warmer name for Steward.

Make Steward welcome everyone who joins the Slack.

**Comment by zachlatta** [comment]
What if we just called Steward "Hubot"?

/cc @MaxWofford

**Comment by zachlatta** [comment]
_From @MaxWofford on November 4, 2015 19:23_

What if we called it `yo`. It's quick to type, and won't seem like a human.

**Comment by zachlatta** [comment]
I don't think there'll be too much confusion as to whether it's a human because Slack has a `bot` tag it puts next to its username and its profile picture is a robot.

Is your biggest complaint about calling it Hubot the length of the name?

**Comment by zachlatta** [comment]
_From @MaxWofford on November 4, 2015 19:25_

Also, nothing would be more amazing than this:
```
@msw: yo pug me
@yo(bot):
```
 ![](https://media.giphy.com/media/w7Y4xlQZG7qGA/giphy.gif)

**Comment by zachlatta** [comment]
_From @MaxWofford on November 4, 2015 19:25_

@zachlatta Mostly name length.
EDIT: What about `bot`

**Comment by zachlatta** [comment]
What about autocompletion? You should be able to type `hu<tab>` and have it autocomplete.

**Comment by zachlatta** [comment]
_From @MaxWofford on November 4, 2015 19:35_

@zachlatta I guess so.

**Comment by zachlatta** [comment]
Going to go ahead with Hubot for now. Also, @hellyeah, @ssun098 was saying that she didn't like how there was a bot that welcomed people and asked them to introduce themselves in the #hackers Slack.

**Comment by ssun098** [comment]
@hellyeah @zachlatta yeah, I feel like going for a more personal touch would be advantageous.  Having club leaders/club members/internal team welcome people would feel significantly better for both parties.
