### ISSUE TITLE
Collect Attendance and Curriculum Plans

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#287]
## Tuesday Morning

@maxwofford will take lead on sending [this note](https://gist.github.com/MaxWofford/b617a6d2953b176dfb59) through the following
channels and make sure they record their curriculum for this week ASAP.

First email people, then ping on slack and (fb) messager to ask if they have any questions.

The status of this per club leader should be visible for the team.

## Tuesday Night

@jonleung will then correspond with @maxwofford to reach out to club leaders who
did not respond to the initial message

## Tue, Wed, Thu, Fri night

**UNASSIGNED** will reach out after 6pm PT if a given club leader who had a club
meeting did not add either of the following to the spreadsheet:

- what they did
- attendance

## Saturday at 1pm

**UNASSIGNED** will reach out to club leaders over text message who did not add
any of the following information to the spreadsheet:

- what they did
- attendance
- what they plan to do

## Sunday

**UNASSIGNED** will call club leaders who did not add any of the following
information to the spreadsheet:

- what they did
- attendance
- what they plan to do

EDIT by @maxwofford: Added visibility requirement and remove table
EDIT by @maxwofford: Reword Tuesday Morning task
EDIT by @maxwofford: Send followup on slack and messenger

**Comment by paked** [comment]
@jonleung You've mixed up Leila's club with mine. (I'm GRSS, not quite sure what she is)

**Comment by paked** [comment]
And CHE is on their twice. But that may be because of their dual meeting scheme...

**Comment by jonleung** [comment]
@paked thanks for the feedbacks! Fixed and still a work in progress!

**Comment by hellyeah** [comment]
I think it would be coolest if we got them to share their attendance number in slack.

**Comment by jonleung** [comment]
@hellyeah I think I want to keep this as simple as possible to see if _this_ even works. If it turns out that it does, then maybe we can try Slack next week?

**Comment by hellyeah** [comment]
Makes sense. My only other question was why email first vs slack but @maxwofford answered on Slack. 

Can't wait to see how this plan works. It seems solid.

**Comment by MaxWofford** [comment]
@jonleung is still sick, so I'll be annexing this issue

![](https://media.giphy.com/media/DuG8cjSqv3chq/giphy.gif)

It will now be broken up into its individual tasks:

https://github.com/hackedu/meta/issues/288
https://github.com/hackedu/meta/issues/289
https://github.com/hackedu/meta/issues/290
