### ISSUE TITLE
Message labs leaders about new weekly checking method

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#288]
This issue can be completed once the following is complete:

1. [x] https://gist.github.com/MaxWofford/b617a6d2953b176dfb59 is sent out to each of the labs leaders.
2. [ ] ~~Confirmations are received from each of the labs leaders.~~

**Comment by jonleung** [comment]
@MaxWofford could you make it so that it's easy to tell which club leaders have agreed to doing this and which ones haven't yet?

**Comment by MaxWofford** [comment]
Resolved this with @jonleung in person.

**Comment by MaxWofford** [comment]
I've removed the second requirement from the issue
