### ISSUE TITLE
Ping labs directors on Saturday and Sunday about curriculum and attendance

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#289]
This can be closed when each of the labs directors who haven't filled out their club data on the day their club meets is sent a text message.

We have data from:
- USC Hybrid High School

Any clubs we don't get a response from after texting, feel free to call.

**Comment by jonleung** [comment]
@MaxWofford this issue's description doesn't seem to account for pinging club leaders who haven't filled out what they are planning to do in next week's club meeting by Saturday?

**Comment by MaxWofford** [comment]
Resolved with @jonleung in person.
