### ISSUE TITLE
Create reminder to ping clubs each day about attendance and curriculum data

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#290]
This issue can be closed once a daily trigger is set up for reaching out to clubs at 6pm.

**Comment by jonleung** [comment]
@MaxWofford what about the clubs that have already happened yesterday and monday?

**Comment by MaxWofford** [comment]
@jonleung I've messaged clubs that have already met for the week.

**Comment by MaxWofford** [comment]
This isn't relevant anymore
