### ISSUE TITLE
Logo redesign

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#31]
I believe you mentioned this involved typography :-).

**Comment by jonleung** [comment]
Closing because

- lack of activity
-  there seem to be much higher leverage issues to fix

**Comment by zachlatta** [comment]
:+1:

On Tue, Aug 18, 2015 at 11:46 AM, Jonathan Leung <notifications@github.com>
wrote:

> Closed #31 <https://github.com/hackedu/meta/issues/31>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/31#event-385699908>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
