### ISSUE TITLE
Design GitHub workflow workshop

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#32]
Create an outline of our GitHub workflow. I've gone ahead and updated the root issue to reflect this change.

**Comment by MaxWofford** [comment]
@zachlatta It might be good to find out when everyone is free to attend this.

**Comment by zachlatta** [comment]
Good call, will do this.

**Comment by zachlatta** [comment]
@MaxWofford, @jonleung, @benzweig, @gemmabusoni can you all respond to https://doodle.com/39wbyqdu2gbgistb?

**Comment by zachlatta** [comment]
Alright, alright.

- - - - -

New issue:

Create an outline of our GitHub workflow. I've gone ahead and updated the root issue to reflect this change.

**Comment by zachlatta** [comment]
Closed by 9259bfefd0d1b39686c1fbdca768640f9b0a4b6a.
