### ISSUE TITLE
hackEDU applicant workflow should forward to pipedrive automatically

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#34]

**Comment by zachlatta** [comment]
Should we just have applicant emails also send to our Pipedrive email address (in addition to `team@hackedu.us`)?

**Comment by MaxWofford** [comment]
@zachlatta This is good. Is there a way to bbc a specific pipedrive list (`clubs`)?

**Comment by zachlatta** [comment]
Not that I know of. Perhaps we could use https://github.com/GeneralScripting/pipedrive-ruby?

**Comment by zachlatta** [comment]
Can you move this issue to https://github.com/hackedu/website? Closing for now.
