### ISSUE TITLE
Create Separate Google Hangouts Channels

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#39]
@zachlatta, can you add some more channels for google hangout chats?

I see that there are some meetings that are happening at the same time

zach.hackedu.us
https://plus.google.com/hangouts/_/calendar/bmFydXRvMTM3QGdtYWlsLmNvbQ.c9p8cerojob5os43sgafiusud0?authuser=0
jonathan.hackedu.us
https://plus.google.com/hangouts/_/calendar/bmFydXRvMTM3QGdtYWlsLmNvbQ.mn6mjcum4pebj66obvefogs5us?authuser=0

**Comment by zachlatta** [comment]
Added to the backlog of hackedu/pm#18, will try to get to in this sprint. If not, next sprint.

**Comment by zachlatta** [comment]
Alright, I finally got to this, haha.

I ended up creating new calendar events with video calls for each member of the team and setting up the DNS with those calendar events (they're all on 01.01.18).

- https://dave-partytime.hackedu.us
- https://gemma-partytime.hackedu.us
- https://jonathan-partytime.hackedu.us
- https://max-partytime.hackedu.us
- https://zach-partytime.hackedu.us

/cc @MaxWofford @gemmabusoni @hellyeah

**Comment by hellyeah** [comment]
this is sweet

**Comment by jonleung** [comment]
@zachlatta I get an error when I try to join my hangout (`https://jonathan-partytime.hackedu.us`)

See the below screenshots:

First, I get this:

![](https://s3.amazonaws.com/f.cl.ly/items/1s3w2W3z1y123k3u400L/Image%202015-08-20%20at%2010.24.51%20AM.png)

Then after a couple of minutes, I get this:

![](https://s3.amazonaws.com/f.cl.ly/items/2a2i2C3U2S0B2F2U2b2T/Image%202015-08-20%20at%2010.23.51%20AM.png)

**Comment by zachlatta** [comment]
Argh, that's unfortunate. I'll look into this first thing.

**Comment by zachlatta** [comment]
Alright, I went ahead and looked into this. I think Google changed something on their end, I've been unable to create any persistent hangout URLs.

All of the above links worked last night. I'm going to go ahead and give up on this for now. If anyone has any suggestions, please let me know! Happy to reopen this.

For now, we just have https://partytime.hackedu.us.

**Comment by MaxWofford** [comment]
https://partytime.hackedu.us gives me:
![screenshot 2015-08-24 at 10 18 00 am](https://cloud.githubusercontent.com/assets/5891442/9446937/6f08ae50-4a49-11e5-9737-c4e1aaa54796.png)

**Comment by zachlatta** [comment]
I just worked with you to get this resolved in a hangout :-). I believe the
issue is that your laptop cached an old hangout link and was sending you to
the now-defunct hangout.

On Mon, Aug 24, 2015 at 10:18 AM, Max Wofford <notifications@github.com>
wrote:

> https://partytime.hackedu.us gives me:
> [image: screenshot 2015-08-24 at 10 18 00 am]
> <https://cloud.githubusercontent.com/assets/5891442/9446937/6f08ae50-4a49-11e5-9737-c4e1aaa54796.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/39#issuecomment-134306048>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, I'm using a private browsing tab and when I go to `https://jonathan-partytime.hackedu.us` I get this:

![image](https://cloud.githubusercontent.com/assets/654941/9475974/df133c6c-4b1e-11e5-8ebb-46599ab371df.png)

**Comment by MaxWofford** [comment]
@jonleung :
> Alright, I went ahead and looked into this. I think Google changed something on their end, I've been unable to create any persistent hangout URLs.

> All of the above links worked last night. I'm going to go ahead and give up on this for now. If anyone has any suggestions, please let me know! Happy to reopen this.

> For now, we just have https://partytime.hackedu.us.

-@zachlatta
