### ISSUE TITLE
Send out hackEDU progress update

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#40]
To Supporters (like Geoff, Kat, Kate)
To People Who've Helped us (Susan)
To Funders

@ZachLatta, what are your thoughts on making something like this?

**Comment by zachlatta** [comment]
I'm in. Added to this week's sprint backlog and will make it into next
week's sprint.

**Comment by MaxWofford** [comment]
Do we want to put this in the email list, or a page on the website?

**Comment by zachlatta** [comment]
Emails! We could have a general newsletter for people who have signed up
on our site as well. The biggest difference between the newsletters for
the different groups will likely be how we aggregate/convey the
information (as in wording, brevity, and format).

**Comment by jonleung** [comment]
@zachlatta thoughts on moving this to Backlog?

**Comment by zachlatta** [comment]
I'd like to keep it in todo, I really do need to update our donors/backers/advisors with what's up.

**Comment by zachlatta** [comment]
I've started sending small updates to backers and advisors. Will continue doing this and track progress here.
