### ISSUE TITLE
Internships

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#42]
Should we have an internships program this summer?

---

I don't think so. I think it'll take too much effort from our end with too little return. Looping @jonleung and @MaxWofford into this.

**Comment by MaxWofford** [comment]
@zachlatta What does this entail? Are we helping hackEDU members find internships, or hiring interns? If hiring, what roles would they have?

**Comment by zachlatta** [comment]
Created this thread for @jonleung, I'm not entirely sure what it means either. @jonleung care to fill us in?

**Comment by jonleung** [comment]
Closed for being no longer relevant
