### ISSUE TITLE
Mew.hackedu.us timezone should be updated

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#43]
@zachlatta It would be great if you could change the time on mew. Thanks in advance!

**Comment by zachlatta** [comment]
![recorded](https://cloud.githubusercontent.com/assets/992248/8092599/a1a1e788-0f6f-11e5-87c5-e3e6fbbb3216.gif)

**Comment by MaxWofford** [comment]
Thanks for this @zachlatta!
