### ISSUE TITLE
Create call cheat-sheet

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#51]
Create a document for quick reference (our metrics, our vision/mission, etc.) when on calls.

**Comment by jonleung** [comment]
@MaxWofford is this still relevant?

**Comment by MaxWofford** [comment]
@jonleung Did you mean to close this? 

Reopening because it is relevant, but not immediately needed. That's why its in icebox on ZenHub.

**Comment by jonleung** [comment]
@MaxWofford, I didn't mean to close it. Sorry about that! Leaving this in the icebox sounds good!

**Comment by zachlatta** [comment]
Closing this in favor of #83.
