### ISSUE TITLE
Deprecate #hackedu-standups IRC channel

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#68]
I'd like to propose deprecating the `#hackedu-standups` IRC channel now that we have a consistent standup routine with Kanban (which we should document in the `pm` repo, just created hackedu/pm#26 for this).

Thoughts?

/cc @jonleung @MaxWofford @andreadeng

**Comment by MaxWofford** [comment]
I'm fine with this. What does deprecating look like in terms of an IRC channel - a general consensus to not use it, or something more?

**Comment by jonleung** [comment]
@zachlatta sounds good!
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
@MaxWofford I believe I can set up a channel redirect and eventually
disown the channel.

**Comment by zachlatta** [comment]
Alright, I'll go ahead and do the following to #hackedu-standups:

- Redirect the channel to #hackedu
- Set the channel's topic to say that it's deprecated
- Remove mentions of it from other channels

**Comment by zachlatta** [comment]
I've set the channel's topic to say that it's deprecated and I've removed the mention from it in `#hackedu`. I couldn't figure out how to redirect it, but I think what we have will do for now.
