### ISSUE TITLE
Assign someone to run standups tomorrow (07.03.15)

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#77]

**Comment by MaxWofford** [comment]
It seems kinda unsustainable to make an issue for this sort of thing every day. I'm happy to lead tomorrow, but why don't we do something like this in IRC?

**Comment by zachlatta** [comment]
@MaxWofford agreed - for now I'll just assign people for the next week and we can address this later.

**Comment by zachlatta** [comment]
Alright, assigned @andreadeng for tomorrow and assigned people for the next week.
