### ISSUE TITLE
Have a discussion about how to make the payments of salaries more transparent.

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#80]
Jonathan's current problems:
- I don't know which months I've been paid for
- I don't know when I'm going to get paid next
- I don't know if there's a date in the month I'm supposed to be paid by

If we can setup a system that will enable me to know the above questions and for the information to be guaranteed to always be updated, I will feel a lot more comfortable. Right now I'm having difficulties having enough money / knowing when I might be able to pay rent and that's a bit scary for me.

**Comment by zachlatta** [comment]
Agreed that we certainly need to clarify this. I have an independent contractor agreement drafted up and will send it to you when I get home tonight that clarifies all of this.

I'll also just mailed you the check for July. It'll be delivered by the 14th.
