### ISSUE TITLE
Introduce me to the chief evangelist for AWS

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#88]
It'd be great if you could introduce me to the chief evangelist for AWS over email – would love to chat with them and see if they might be interested in continually supporting us.

**Comment by jonleung** [comment]
@zachlatta, can you give me an intro email that you want me to send for this and I'll send it?

**Comment by zachlatta** [comment]
Any chance you could make the intro directly and just write a brief thing?

Perhaps something along the lines of:

> Hey X,
>
> I'd like to introduce you to my cofounder, Zach, who'd like to briefly
talk with you about what we're working on together and learn more about
AWS's support of other nonprofits.

Maybe not that exact wording – you have a different writing style than me.

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us/>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
Closing because Zach already has a connection to AWS now.
