### ISSUE TITLE
CHE Hacks Fiscal Sponsorship

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#90]
Moved from hackedu/hack-camp#186.

/cc @jonleung

**Comment by MaxWofford** [comment]
@zachlatta Are we sponsoring CHE hacks? or are they sponsoring us?
/cc @jonleung

**Comment by zachlatta** [comment]
As discussed this evening in-person with @MaxWofford and @jonleung, we don't have the bandwidth to do this and it'd be dubiously possible with our fiscal sponsorship agreement.
