### ISSUE TITLE
Create mockup of home page redesign

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#91]
Create an image mockup (Illustrator/Photoshop/etc) of a redesign of the https://hackedu.us homepage.

Moved from hackedu/hack-camp#175.

**Comment by MaxWofford** [comment]
Why is this in https://github.com/hackedu/meta instead of https://github.com/hackedu/website?

cc/ @andreadeng @zachlatta

**Comment by zachlatta** [comment]
Argh, I'm dumb.

Yeah, that should be in https://github.com/hackedu/website.

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us/>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
