### ISSUE TITLE
Ask about in-kind GitHub donation

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#92]
Can you email your contact at GitHub to see if they may be interested in donating repos to us?

**Comment by jonleung** [comment]
@zachlatta, just wanted to say I saw this. Will email them when I reach this task in the todo queue!

**Comment by zachlatta** [comment]
Sounds good!

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Got it donated. We now have free private repos.

**Comment by jonleung** [comment]
:+1:
