### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#93]
This is terrible programmer art, but thoughts on this?

![hackedu](https://cloud.githubusercontent.com/assets/992248/9004836/5a69a5b8-372e-11e5-9962-0fe744bcae93.png)

![hackedu](https://cloud.githubusercontent.com/assets/992248/9004868/9c5bf7fa-372e-11e5-8565-08ca6f4a5b8b.png)

![hackedu](https://cloud.githubusercontent.com/assets/992248/9004907/d70c64e8-372e-11e5-9dd8-312de9623465.png)

/cc @MaxWofford @andreadeng @jonleung

**Comment by zachlatta** [comment]
Playing around a bit more. I'm so sorry.

![hackedu](https://cloud.githubusercontent.com/assets/992248/9004979/55433a1c-372f-11e5-9cc4-1334368f74b5.png)

**Comment by zachlatta** [comment]
Looping in Ben as well.

/cc @benzweig

**Comment by MaxWofford** [comment]
I'm a fan of the third one: 
<img src="https://cloud.githubusercontent.com/assets/992248/9004907/d70c64e8-372e-11e5-9dd8-312de9623465.png" width="64">

**Comment by MaxWofford** [comment]
@zachlatta What is the best ZenHub board to put this in?

**Comment by zachlatta** [comment]
Hmm... I'd probably just put this in the icebox for now.

I'm also partial towards the third one. The thing I like about this logo is
that we can change its color and it is still legible.

Should we play around with font at all?

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Ping on this. Any additional thoughts?

**Comment by MaxWofford** [comment]
I'm partial to keeping the `h` lowercase if possible, but it looks nice capitalized here.

**Comment by jonleung** [comment]
@zachlatta @MaxWofford I personally am not a big fan of any of these. My suggestion would be to table this until later in year, perhaps for our 2016 launch.

**Comment by MaxWofford** [comment]
@zachlatta What if we put these is a PR for the `logos` folder for the time being?

**Comment by zachlatta** [comment]
I think it'd only really make sense to create a PR for them if we were planning on moving forward with these logos.

**Comment by MaxWofford** [comment]
@zachlatta Are these (archived) in the dropbox? If so, I think we can close this issue.

**Comment by zachlatta** [comment]
Closing's a good call.
