### ISSUE TITLE
Add `awaiting merge` tag in hackedu/hack-camp

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/meta#98]
It seems like it would be good to have an `awaiting merge` tag in hackedu/hack-camp. Less issues labeled as `blocking` = more win.

@hackedu/hack-camp Thoughts?

**Comment by MaxWofford** [comment]
If there aren't any cons to this brought up by EOD I'll add the label tonight.

**Comment by jonleung** [comment]
:+1:

**Comment by MaxWofford** [comment]
Added an `awaiting merge` label to hacked/hack-camp

https://github.com/hackedu/hack-camp/labels

**Comment by zachlatta** [comment]
Cool with me.

On Mon, Aug 10, 2015 at 11:48 PM, Max Wofford <notifications@github.com>
wrote:

> Added an awaiting merge label to hacked/hack-camp
>
> https://github.com/hackedu/hack-camp/labels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/98#issuecomment-129729510>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
